### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by zzl1787** [michalmiklas/atlas-docker#2]
Hi, @michalmiklas, I tried the latest v1.1.0 docker image. The atla-server was successfully started, but I couldn't open the web ui on `localhost:21000`. 
Any replies will be appreciated!

**Comment by zzl1787** [comment]
I was wrong. It works ,actually.

**Comment by michalmiklas** [comment]
yep, I was just gonna respond. gave it a try and it worked as expected.
